name: Publish Alpine to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "Alpine/*"
      - ".github/workflows/Alpine.yml"
  pull_request:
    branches:
      - main
    paths:
      - "Alpine/*"
      - ".github/workflows/Alpine.yml"
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get Current Time
        id: get_time
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Build and Push Alpine Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64, linux/arm64
          push: ${{github.ref == 'refs/heads/main'}}
          tags: vineelsai/alpine:latest, vineelsai/alpine:${{ steps.get_time.outputs.date }}
          file: ./Alpine/Dockerfile
