name: Publish Arch to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "Arch/*"
      - ".github/workflows/Arch.yml"
  pull_request:
    branches:
      - main
    paths:
      - "Arch/*"
      - ".github/workflows/Arch.yml"
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get Current Time
        id: get_time
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Build and Push Arch Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: ${{github.ref == 'refs/heads/main'}}
          tags: vineelsai/arch:latest, vineelsai/arch:${{ steps.get_time.outputs.date }}
          file: ./Arch/Dockerfile

      - name: Build Arch Arm64 Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: false
          load: true
          tags: vineelsai/arch:arm64
          file: ./Arch/Dockerfile.arm64

      - name: Extract and Push Arch Arm64 Image
        run: |
          docker create --platform linux/arm64 --name arch-arm64 vineelsai/arch:arm64 bash
          docker export arch-arm64 | docker import - vineelsai/arch:arm64
          docker export arch-arm64 | docker import - vineelsai/arch:arm64-${{ steps.get_time.outputs.date }}
          if [[ "${{github.ref == 'refs/heads/main'}}" == "true" ]]; then
            docker push vineelsai/arch:arm64
            docker push vineelsai/arch:arm64-${{ steps.get_time.outputs.date }}
          fi
