name: Publish Arch to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "Arch/*"
      - ".github/workflows/Arch.yml"
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get Current Time
        id: get_time
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Build and Push Arch Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: vineelsai/arch:latest, vineelsai/arch:${{ steps.get_time.outputs.date }}
          file: ./Arch/Dockerfile

      - name: Build and Push Arch Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          push: true
          tags: vineelsai/arch:arm64, vineelsai/arch:arm64-${{ steps.get_time.outputs.date }}
          file: ./Arch/Dockerfile.arm64
