name: Publish Dev to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "Dev/*"
      - ".github/workflows/Dev.yml"
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get Current Time
        id: get_time
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Build and Push Dev Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: vineelsai/dev:latest, vineelsai/dev:ubuntu, vineelsai/dev:${{ steps.get_time.outputs.date }}, vineelsai/dev:ubuntu-${{ steps.get_time.outputs.date }}
          file: ./Dev/Dockerfile
